nodes:
  # Wazuh indexer nodes
  indexer:
    - name: siem.dcnetwork.local
      ip: 10.0.1.211
    #- name: node-2
    #  ip: <indexer-node-ip>
    #- name: node-3
    #  ip: <indexer-node-ip>

  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  server:
    - name: siem.dcnetwork.local
      ip: 10.0.1.211
    #  node_type: master
    #- name: wazuh-2
    #  ip: <wazuh-manager-ip>
    #  node_type: worker
    #- name: wazuh-3
    #  ip: <wazuh-manager-ip>
    #  node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: siem.dcnetwork.local
      ip: 10.0.1.211
